spring:
  data:
    mongodb:
      uri: mongodb+srv://<db_user>:<db_password>@cluster0.m32af.mongodb.net/unam_app
      database: unam_app
      username: <db_user>
      password: <db_password>

server:
  port: 8081
